# Copyright (C) 2019 Knot.x Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

trigger:
  - master
  - milestone/extension-with-graph-status-panel

pool:
  vmImage: 'ubuntu-latest'

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn
  NODE_VERSION: 12.x

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(NODE_VERSION)
  - task: Cache@2
    inputs:
      key: 'yarn | "$(Agent.OS)" | "$(node_version)" | yarn.lock'
      restoreKeys: |
        yarn | "$(Agent.OS)" | "$(node_version)"
        yarn
      path: $(YARN_CACHE_FOLDER)
    displayName: Cache Yarn packages
  - script: yarn install --frozen-lockfile
    displayName: "Install dependencies."
  - script: yarn run dev
    displayName: "Build"
  - script: yarn run test
    displayName: "Test"
  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'test-report.xml'
      testRunTitle: 'React tests'